name: Bug Report
description: Create a report of unintended behavior or problems
labels: [bug]
body:
  - type: input
    attributes:
      label: Browser and version
      placeholder: e.g. Chrome 94
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug/issue
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproducing
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: textarea
    attributes:
      label: Console logs
      description: Press F12 and go to the Console tab, then copy or screenshot the logs. This helps us quickly identify the cause of the bug.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.